* File: inv.pex.netlist.INV.pxi
* Created: Wed Mar 23 15:28:51 2022
* 
x_PM_INV%IN N_IN_MM5_g N_IN_MM4_g IN PM_INV%IN
x_PM_INV%GND N_GND_MM5_b N_GND_MM5_s GND PM_INV%GND
x_PM_INV%VDD N_VDD_MM4_b N_VDD_MM4_s VDD PM_INV%VDD
x_PM_INV%OUT N_OUT_MM4_d N_OUT_MM5_d OUT PM_INV%OUT
